#!/bin/sh
shell="$1"

if [ "$shell" = "" ]; then
  echo "usage: install-completion <shell>"
  exit
fi

completion=$(novasearch completion "$shell")

# check completion shell
if ! command -v "$shell" >/dev/null; then
  echo "$shell could not be found"
  exit
fi

# install completion
case "$shell" in
bash)
  echo "$completion" | sudo tee /etc/bash_completion.d/novasearch
  ;;
zsh)
  echo "$completion" | sudo tee /usr/share/zsh/site-functions/_novasearch
  ;;
fish)
  echo "$completion" | sudo tee /usr/local/share/fish/vendor_completions.d/novasearch.fish
  ;;
powershell)
  echo "$completion" | sudo tee /usr/local/share/powershell/Modules/novasearch/novasearch.psm1
  ;;
*)
  echo "unsupported shell"
  exit
  ;;
esac
